#ifndef SIMD_OS_LINUX_HPP_
#define SIMD_OS_LINUX_HPP_

#define LINUX_DLL_EXPORT
#define LINUX_DLL_IMPORT

#ifdef SIMD_API_BUILD
#define SIMD_API LINUX_DLL_EXPORT
#else
#define SIMD_API LINUX_DLL_IMPORT
#endif

#endif /* SIMD_OS_LINUX_HPP_ */